version: '3'

services:
    iobroker:
        restart: always
        build: ./iobroker
        container_name: iobroker-i2c
        hostname: iobroker-i2c
        ports:
            - '8081:8081'
        volumes:
            - ./..:/workspace:cached
            - iobrokerdata-i2c:/opt/iobroker
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Zurich
            - SETGID=1000
    parcel:
        restart: always
        build: ./parcel
        ports:
            - '1234:1234'
        volumes:
            - ./..:/workspace:cached

volumes:
    iobrokerdata-i2c:
