version: '3'

services:
    iobroker:
        build: ./iobroker
        container_name: iobroker-i2c
        hostname: iobroker-i2c
        expose:
            - 8081
        volumes:
            - ..:/workspace:cached
            - iobrokerdata-i2c:/opt/iobroker
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Zurich
            - SETGID=1000
    parcel:
        container_name: parcel-i2c
        build: ./parcel
        expose:
            - 1234
        ports:
            - '1235:1235'
        volumes:
            - ..:/workspace:cached

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
            - parcel
        links:
            - iobroker
            - parcel
        container_name: nginx-i2c
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace:cached
        ports:
            - 8081:80

volumes:
    iobrokerdata-i2c:
